/* eslint-disable */
export default {
    "WaitListGeneration": "Please wait... SharePoint Lists will be generated soon.",
    "Wait": "Wait",
    "ListGenError": "Lists generation error",
    "ListExtError": "Checking list existence error",
    "Topics": "Topics",
    "Posts": "Posts",
    "By": "By",
    "NewForum": "New Forum",
    "Required": " is required",
    "Close": "Close",
    "NotInTeams": "Not in Microsoft Teams",
    "NewTopic": "New Topic",
    "TopicsPosts": "Topics/Posts",
    "LastPost": "Last Post",
    "RepliesViews": "Replies/Views",
    "Views": "Views",
    "Subject": "Subject",
    "Message": "Message",
    "Forum": "Forum",
    "EditTopic": "Edit Topic",
    "UpdateForum": "Update Forum",
    "Delete": "Delete",
    "Forums": "Forums",
    "UpdateTopic": "Update Topic",
    "Replies": "Replies",
    "UpdatePost": "Update Post",
    "Reply": "Reply",
    "EditPost": "Edit Post",
    "ReplyPost": "Reply Post",
    "NotAnswered": "Not Answered",
    "Answered": "Answered",
    "Name": "Name",
    "Description": "Description",
    "Title": "Title",
    "TabDisplayName": "Tab Display Name",
    "DefaultTabDisplayName": "Microsoft Teams Basic Forum",
    "Bot": "Bot"
}